version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${PORT_DB}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: spring-backend
    restart: always
    ports:
      - "${PORT_BACKEND}:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_URI=${DB_URI}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DRIVER=${DB_DRIVER}


  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    container_name: react-frontend
    restart: always
    ports:
      - "${PORT_FRONTEND}:80"
    depends_on:
      - backend


volumes:
  db_data:

